BeautySpaceInfrastructure/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeautySpaceDomain.Model;
using BeautySpaceInfrastructure;
using BeautySpaceInfrastructure.Services;

namespace BeautySpaceInfrastructure.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly DbbeautySpaceContext _context;
        private CategoryDataPortServiceFactory _categoryDataPortServiceFactory;

        public CategoriesController(DbbeautySpaceContext context)
        {
            _context = context;
            _categoryDataPortServiceFactory = new CategoryDataPortServiceFactory(context);
        }



        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Services", new { id = category.Id, name = category.Name});
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (_context.Categories.Any(ts => ts.Name == category.Name))
                {
                    ModelState.AddModelError("Name", "Категорія з такою назвою вже існує");
                    ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name");
                    return View(category);
                }

                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (_context.Categories.Any(c => c.Name == category.Name && c.Id != category.Id))
                {
                    ModelState.AddModelError("Name", "Категорія з такою назвою вже існує");
                    ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name");
                    return View(category);
                }

                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories
                .Include(c => c.Services)
                    .ThenInclude(s => s.EmployeeServices)
                        .ThenInclude(es => es.TimeSlots)
                            .ThenInclude(ts => ts.Reservations)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (category != null)
            {
                foreach (var service in category.Services)
                {
                    foreach (var employeeService in service.EmployeeServices)
                    {
                        _context.TimeSlots.RemoveRange(employeeService.TimeSlots);
                    }
                    _context.EmployeeServices.RemoveRange(service.EmployeeServices);
                }
                _context.Services.RemoveRange(category.Services);
                _context.Categories.Remove(category);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel, CancellationToken cancellationToken = default)
        {
            if (fileExcel == null || fileExcel.Length == 0)
            {
                TempData["ErrorMessage"] = "Файл для імпорту не обрано.";
                return RedirectToAction(nameof(Import));
            }

            try
            {
                var importService = _categoryDataPortServiceFactory.GetImportService(fileExcel.ContentType);
                using var stream = fileExcel.OpenReadStream();
                bool isNewServiceCreated = await importService.ImportFromStreamAsync(stream, cancellationToken);

                TempData["SuccessMessage"] = isNewServiceCreated ? "Імпорт завершено успішно! Нові дані були додані." : "Всі дані з файлу вже зберігаються в системі.";
            }
            catch (ArgumentException ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            catch (NotImplementedException ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Export([FromQuery] string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    CancellationToken cancellationToken = default)
        {
            var exportService = _categoryDataPortServiceFactory.GetExportService(contentType);

            var memoryStream = new MemoryStream();

            await exportService.WriteToAsync(memoryStream, cancellationToken);

            await memoryStream.FlushAsync(cancellationToken);
            memoryStream.Position = 0;

            return new FileStreamResult(memoryStream, contentType)
            {
                FileDownloadName = $"categories_{DateTime.UtcNow.ToShortDateString()}.xlsx"
            };
        }

        [HttpGet]
        public async Task<bool> CheckReservations(int categoryId)
        {
            var category = await _context.Categories.Include(c => c.Services).ThenInclude(s => s.EmployeeServices).ThenInclude(es => es.TimeSlots).ThenInclude(ts => ts.Reservations).FirstOrDefaultAsync(c => c.Id == categoryId);
            if (category != null)
            {
                foreach (var service in category.Services)
                {
                    foreach (var employeeService in service.EmployeeServices)
                    {
                        foreach (var timeSlot in employeeService.TimeSlots)
                        {
                            if (timeSlot.Reservations.Any())
                            {
                                return true;
                            }
                        }
                    }
                }
            }

            return false;
        }
    }
}

BeautySpaceInfrastructure/Views/Categories/Create.cshtml
@model BeautySpaceDomain.Model.Category

@{
    ViewData["Title"] = "Створення категорії";
}


<div class="content">
    <h4>Створення нової категорії</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="edit-create-or-back">
                    <input type="submit" value="Створити" class="btn btn-primary" />
                    <a class="btn-back-new" asp-action="Index">Скасувати</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeautySpaceInfrastructure/Views/Categories/Delete.cshtml
@model BeautySpaceDomain.Model.Category

@{
    ViewData["Title"] = "Видалення категорії";
}

<div class="content">
    <div>
        <h4>Видалення категорії</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <div class="delete-or-back">
            <form id="deleteForm" asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <a class="btn" asp-action="Index">Назад</a>
            </form>
            <button class="btn btn-danger" onclick="confirmDelete() ">Видалити</button>
        </div>

    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confirmDelete() {
            $.ajax({
                url: '/Services/GetServiceCount',
                type: 'GET',
                data: { categoryId: @Model.Id },
                success: function (servicesCount) {
                    if (servicesCount > 0) {
                        $.ajax({
                            url: '/Categories/CheckReservations',
                            type: 'GET',
                            data: { categoryId: @Model.Id },
                            success: function (hasReservations) {
                                if (hasReservations) {
                                    Swal.fire({
                                        title: 'Помилка',
                                        text: "Не можна видалити категорію якщо до неї прив'язані бронювання.",
                                        icon: 'error',
                                        confirmButtonColor: '#ab0c24',
                                        confirmButtonText: 'OK'
                                    })
                                } else {
                                    Swal.fire({
                                        title: 'Підтвердження видалення',
                                        text: "Якщо ви видалите цю категорію всі послуги, працівники цієї послуги та їхні таймслоти будуть втрачені.",
                                        icon: 'warning',
                                        showCancelButton: true,
                                        confirmButtonColor: '#ab0c24',
                                        cancelButtonColor: '#6d6d6d',
                                        confirmButtonText: 'Видалити категорію',
                                        cancelButtonText: 'Cкасувати видалення'
                                    }).then((result) => {
                                        if (result.isConfirmed) {
                                            document.getElementById('deleteForm').submit();
                                        }
                                    })
                                }
                            }
                        });
                    } else {
                        document.getElementById('deleteForm').submit();
                    }
                }
            });
        }

    </script>
}

BeautySpaceInfrastructure/Views/Categories/Details.cshtml
@model BeautySpaceDomain.Model.Category

@{
    ViewData["Title"] = "Деталі категорії";
}

<div class="content">

    <div>
        <h4>Деталі категорії</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>
    <div>
        @if (Accessibility.AllExceptUser(User))
        {
            <a class="btn-back-new" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
        }

        <a class="btn-back-new" asp-action="Index">Назад</a>
    </div>
</div>

BeautySpaceInfrastructure/Views/Categories/Edit.cshtml
@model BeautySpaceDomain.Model.Category

@{
    ViewData["Title"] = "Редагування категорії";
}

<div class="content">
    <h4>Редагування категорії</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="edit-create-or-back">
                    <input type="submit" value="Зберегти зміни" class="btn btn-outline-primary" />
                    <a class="btn-back-new" asp-action="Index">Скасувати зміни</a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeautySpaceInfrastructure/Views/Categories/Import.cshtml
@model BeautySpaceDomain.Model.Category

@{
    ViewData["Title"] = "Імпорт даних про категорії послуг";
    var errorMessage = TempData["ErrorMessage"] as string;

}

<div class="content">
    <h1>Імпорт</h1>

    <div>
        <h3>Оберіть excel-файл для завантаження</h3>
        @using (Html.BeginForm("Import", "Categories", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
        {
            <div>
                Завантажте Excel-файл:
                <input type="file" name="fileExcel" id="fileExcel" accept=".xlsx, .xls" />
                <div>
                    <input type="submit" value="Завантажити" />
                </div>
            </div>
        }

        <div class="error-message">
            @if (ViewBag.Error != null)
            {
                var errors = ViewBag.Error.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var error in errors)
                {
                    <div class="alert alert-danger">@error</div>
                }
            }
        </div>
    </div>



    @if (!string.IsNullOrEmpty(errorMessage))
    {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                var errorMessage = @Html.Raw(Json.Serialize(errorMessage));
                if (errorMessage) {
                    alert(errorMessage);
                }
            });
        </script>
    }
</div>

BeautySpaceInfrastructure/Views/Categories/Index.cshtml
@model IEnumerable<BeautySpaceDomain.Model.Category>

@{
    ViewData["Title"] = "Категорії";
    var successMessage = TempData["SuccessMessage"] as string;

}

<div class="content">
    <h1>Доступні категорії</h1>

    <table class="table">
        <thead>
            <tr>
                <th class="table-name">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @if (Accessibility.AllExceptUser(User))
                    {
                        <a class="btn-new" asp-action="Create">Створити нову категорію</a>
                    }

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div class="actions">
                            <a asp-action="Details" asp-route-id="@item.Id">Переглянути послуги</a>

                            @if (Accessibility.AllExceptUser(User))
                            {
                                <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a>
                                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>



   

    @if (Accessibility.AllExceptUser(User))
    {
        <div style="display:flex; gap:20px;">
            <a class="btn btn-outline-primary" type="=submit" asp-area="" asp-controller="Categories" asp-action="Import">Завантажити з файлу</a>
            <a class="btn btn-outline-primary" type="=submit" asp-area="" asp-controller="Categories" asp-action="Export">Експортувати у файл</a>
        </div>
        <div class="categoryChart">
            <div id="CategoryChart"></div>
        </div>

    }




    @if (!string.IsNullOrEmpty(successMessage))
    {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                var successMessage = @Html.Raw(Json.Serialize(successMessage));
                if (successMessage) {
                    alert(successMessage);
                }
            });
        </script>
    }


</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


    <script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            $.get('/api/Charts/JsonDataCategory')
                .done(function (JsonDataCategory) {
                    var data = google.visualization.arrayToDataTable(JsonDataCategory, false);
                    var options = {
                        title: "Співвідношення між категоріями та кількістю послуг",
                        width: 500,
                        height: 400
                    };
                    var chart = new google.visualization.PieChart(document.getElementById('CategoryChart'));
                    chart.draw(data, options);
                })
                .fail(function (error) {
                    console.error('Error loading data:', error);
                });
        }
    </script>




}